# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: pujanshah3333/workflow/.github/workflows/prepare_terraform.yml@main
        with:
          role_to_assume: arn:aws:iam::12345:role/test
        secrets:
          submodule_token: qweqweqwe
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
