name: Prepare terraform
on:
  workflow_call:
    inputs:
      role-to-assume:
        required: true
        type: string
      aws-region:
        default: 'eu-central-1'
        required: false
        type: string
      terraform-version:
        default: '0.14.8'
        required: false
        type: string
    secrets:
      submodule_token:
        required: true
jobs:
  prepare_terraform:
    name: Prepare for terraform run
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.submodule_token }}
          submodules: true
      # - uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     role-to-assume: ${{ inputs.role-to-assume }}
      #     aws-region: ${{ inputs.aws-region }}
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.terraform-version }}
