name: Prepare terraform
on:
  workflow_call:
    inputs:
      role_to_assume:
        required: true
        type: string
      run:
        required: true
        type: string
      environment:
        required: false
        type: string
      aws_region:
        default: 'eu-central-1'
        required: false
        type: string
      terraform_version:
        default: '0.14.8'
        required: false
        type: string
    secrets:
      submodule_token:
        required: true
      account_id:
        required: true
jobs:
  prepare_terraform:
    environment: ${{ inputs.environment }}
    name: Prepare for terraform run
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.submodule_token }}
          submodules: true
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.account_id }}:role/${{ inputs.role_to_assume }}
          aws-region: ${{ inputs.aws_region }}
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ inputs.terraform_version }}
      - run: ${{ inputs.run }}
